### ISSUE TITLE
pull requestのラベルを貼れない

### ISSUE THREAD

**Issue by tatsuo-ishii** [pgsql-jp/jpug-doc#1397]
## 問題点

pull requestに自分でラベルを貼れない

## 背景

このプロジェクトでは、pull requestに自分でラベルを貼ることを推奨していますが、jpug-docリポジトリにadminまたはwrite権限を持つ人以外はラベルを貼れないようです。
なので、一般の人(read 権限しか持っていない)からpull requstを出していただいてもその方は自分でラベルを貼れません。

## 解決方法

oraganizationのteam機能を使えば、teamにpull requestを出しているユーザを加えることによりラベルが貼れるようになりますが、oraganization機能は有料なので、JPUGの予算が付かない限り利用できません。

jpug-docリポジトリにadminまたはwrite権限を持つユーザにラベル貼りを依頼するようなワークフローに変更する必要がありそうです。

**Comment by harukat** [comment]
有料機能を使うこと自体は、必要なら予算要請のうえ遠慮せずどんどん使っていく方針で良いと思います。JPUGのお金は有意義に使ってこそ協賛企業の意に沿うと思いますので。

あとは、write権限を付与しない人をラベルを貼り替えていくレビュー～マージまでの活動に巻き込んでいくかどうか？ という運用上のやり方についての得失賛否で考えていけば良いかと思います。

**Comment by harukat** [comment]
ユーザに「ラベルを自由に貼れるけれども、マージや直接コミットはできない」という権限の与え方が無償の範囲できないことが問題、ということですね。

**Comment by noborus** [comment]
GithubのAPIでラベルを貼ることが可能だと思いますので、自動で付けるようにしたらどうかと考えていました。
現在Travis-CIが動作していて、これはpull request（やその後の修正コミット）で呼び出されるので、その結果によりラベルを貼るAPIをたたけば出来るのではないかと思います。

**Comment by tatsuo-ishii** [comment]
> GithubのAPIでラベルを貼ることが可能だと思いますので、自動で付けるようにしたらどうかと考えていました。
それができるなら、コミッターにおいてもラベルを手動で貼ったり、貼り直す手間が省けるので嬉しいですね！

**Comment by ren3-k** [comment]
GitHub ActionsとGitHub APIを使用して、Pull Requestに対して自動でラベルを付けることができましたのでご報告いたします。
GitHub APIは、GitHubホストランナーの仮想マシン上で実行します。
GitHub APIの実行に必要な情報(GitHubコンテキスト)は、GitHub Actionsのワークフローから環境変数としてGitHubホストランナーの仮想マシンへ渡せます。
要はこれさえできれば後はいかようにも、という感じですが参考程度にワークフロー定義ファイルと自動でラベルを付けるプログラムを記載します。

GitHub Actionsの実行は、`.github/workflows`  ディレクトリ内にYAMLファイル作成します。
※APIを実行するプログラムは何でもよいと思いますが、PyGithubが簡単そうだったのでPythonにしました。
`pull_request.yml`
```
name: Pull request automate set lable

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout automate set label
      uses: actions/checkout@v2
      with:
        repository: xxxx/xxxx # Pull Requestに対して自動てラベルを付けるプログラムのリポジトリ
        path: automate-set-label # チェックアウト先のディレクトリ

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install PyGithub

    - name: Automate set label
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_GITHUB_REPOSITORY: "pgsql-jp/jpug-doc"
        TARGET_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        python ./automate-set-label/automate_set_label.py
```

Pull Requestに対して自動でラベルを付けるプログラム
`automate_set_label.py`
```
from os import environ
from github import Github

ACCESS_TOKEN               = environ.get("ACCESS_TOKEN")
TARGET_GITHUB_REPOSITORY   = environ.get("TARGET_GITHUB_REPOSITORY") 
TARGET_PULL_REQUEST_NUMBER = int(environ.get("TARGET_PULL_REQUEST_NUMBER"))

g = Github(ACCESS_TOKEN)
repo = g.get_repo(TARGET_GITHUB_REPOSITORY)
pr = repo.get_pull(TARGET_PULL_REQUEST_NUMBER)

# ラベル名
awaiting_review   = "レビュー待ち"
awaiting_rereview = "再レビュー待ち"
point_of_order    = "指摘事項あり"

labels = pr.get_labels()
label_num = labels.totalCount

# PR時のラベル名を取得
if label_num == 0:
    label_name = ""
else:
    label_name = labels[0].name

# ラベルを設定
if label_name == "":
    pr.add_to_labels(awaiting_review)
elif label_name == point_of_order:
    pr.remove_from_labels(point_of_order)
    pr.add_to_labels(awaiting_rereview)
```
